/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BudgetRevenueChart: typeof import('./src/components/BudgetRevenueChart.vue')['default']
    CardBody: typeof import('./src/components/ui/card-3d/CardBody.vue')['default']
    CardContainer: typeof import('./src/components/ui/card-3d/CardContainer.vue')['default']
    CardItem: typeof import('./src/components/ui/card-3d/CardItem.vue')['default']
    ChartSection: typeof import('./src/components/ChartSection.vue')['default']
    DirectorAnalysisChart: typeof import('./src/components/DirectorAnalysisChart.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IInput: typeof import('./src/components/ui/input/IInput.vue')['default']
    LanguageDistributionChart: typeof import('./src/components/LanguageDistributionChart.vue')['default']
    MiniCharts: typeof import('./src/components/MiniCharts.vue')['default']
    MovieTable: typeof import('./src/components/MovieTable.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    RevenueChart: typeof import('./src/components/RevenueChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCards: typeof import('./src/components/StatCards.vue')['default']
    WorldMapChart: typeof import('./src/components/WorldMapChart.vue')['default']
  }
}
